### ISSUE TITLE
fragmentB返回数据到fragmentA，有啥方法可以实现吗？

### ISSUE THREAD

**Issue by ifadai** [hegaojian/JetpackMvvm#101]
请教下博主，fragmentA跳转到fragmentB之后，然后fragmentB返回的时候携带数据给FragmentA，类似Activity的setResult(),有啥可以的方案吗？
是使用一个activity级别的viewmodel吗？

**Comment by OJZen** [comment]
我认为确实可以使用一个共享数据的ViewModel来实现，官方文档有提到：[在 Fragment 之间共享数据](https://developer.android.google.cn/topic/libraries/architecture/viewmodel#sharing)。如果使用LiveData共享数据要注意数据倒灌的问题：[UnPeek-LiveData](https://github.com/KunMinX/UnPeek-LiveData)

**Comment by hegaojian** [comment]
@ifadai  demo里面有实现的，demo中默认是用了一个全局的viewmodel去发送livedata ，当然在单Activity中，activity级别的也相当于全局的viewmodel了，
