### ISSUE TITLE
在mainFragment中初始化BottomNavigationViewEx报错

### ISSUE THREAD

**Issue by Travellingpoet** [hegaojian/JetpackMvvm#108]
报错在xml中无法找到bottomNavigationEx，但是通过databinding可以获取到 只有在运行时才报错

**Comment by katoluo** [comment]
Material库升到1.4之后就会，我就改为1.3，就不会报这个错误了。

**Comment by hegaojian** [comment]
这个是 BottomNavigationViewEx 这个库的问题，他的Materia版本太低了，如果还是想用这个库的话，可以使用 https://github.com/CListery/BottomNavigationEx
