### ISSUE TITLE
下载测试

### ISSUE THREAD

**Issue by Rissayao** [hegaojian/JetpackMvvm#113]
java.lang.VerifyError: Verifier rejected class me.hgj.jetpackmvvm.ext.download.DownLoadManager: java.lang.Object me.hgj.jetpackmvvm.ext.download.DownLoadManager.doDownLoad(java.lang.String, java.lang.String, java.lang.String, java.lang.String, boolean, me.hgj.jetpackmvvm.ext.download.OnDownLoadListener, kotlinx.coroutines.CoroutineScope, kotlin.coroutines.Continuation) failed to verify: java.lang.Object me.hgj.jetpackmvvm.ext.download.DownLoadManager.doDownLoad(java.lang.String, java.lang.String, java.lang.String, java.lang.String, boolean, me.hgj.jetpackmvvm.ext.download.OnDownLoadListener, kotlinx.coroutines.CoroutineScope, kotlin.coroutines.Continuation): [0x4CA] register v12 has type Reference: java.lang.Throwable but expected Precise Reference: kotlin.jvm.internal.Ref$ObjectRef (declaration of 'me.hgj.jetpackmvvm.ext.download.DownLoadManager' appears in /data/app/com.seuic.chinapost-2/base.apk)

**Comment by hegaojian** [comment]
下载模块很早就不维护了，可以选择其他方案替代
