### ISSUE TITLE
用协程post请求没问题,get请求不行,没请求成功吧,直接返回200,body为null

### ISSUE THREAD

**Issue by zhangjianzhu** [hegaojian/JetpackMvvm#124]

**Comment by hegaojian** [comment]
这个是你接口规定的要用POST请求，你换成 Get请求导致的问题

**Comment by zhangjianzhu** [comment]
> 这个是你接口规定的要用POST请求，你换成 Get请求导致的问题

不是的呢，具体我也不清楚什么问题，接口就是Get的，我估計可能是我用的库都是最新的，跟Demo里的库有差异吧

**Comment by hegaojian** [comment]
如果不是接口问题，那么返回200 就是OK的，只是在返回的json中，可能你没有用正确的类型接收导致解析失败，如果返回的 data为null的话，在定义接口的时候，应该给接收的泛型里面加可空标识，例如 ApiResponse<XXX?>

**Comment by zhangjianzhu** [comment]
> 如果不是接口问题，那么返回200 就是OK的，只是在返回的json中，可能你没有用正确的类型接收导致解析失败，如果返回的 data为null的话，在定义接口的时候，应该给接收的泛型里面加可空标识，例如 ApiResponse<XXX?>
都试过了，就我们的框架请求get不行，像浏览器啊 postman之类的请求都是正常的呢，我用原始的网络请求是正常的，就很难受
