### ISSUE TITLE
鸡哥，请教几个接口问题

### ISSUE THREAD

**Issue by axb996** [hegaojian/JetpackMvvm#142]
如图：
![2024-05-15_130320](https://github.com/hegaojian/JetpackMvvm/assets/60745027/bda4d7f0-3f02-4395-8be7-b21fb25d2dbd)

**Comment by dyj0816** [comment]
第一个问题可以用okhttp的拦截器（Interceptor），公共参数直接在拦截器添加就行。第二个我认为除开公共参数，其他的还是写进去比较好，说真的，这么几个接口过段时间你再看就懵逼了，还不如显明一点
