### ISSUE TITLE
作者考虑加paging吗？

### ISSUE THREAD

**Issue by 8debug** [hegaojian/JetpackMvvm#15]
期待全套jetpack

**Comment by hegaojian** [comment]
paging后期有时间会考虑加上的，全套的话我在想到底要不要集成这么多

**Comment by 8debug** [comment]
如果有全套，那这个项目的学习价值更高了

**Comment by 8debug** [comment]
Room也可以有，哈哈

**Comment by hegaojian** [comment]
其实感觉 paging和room官方已经封装的很好了，现在就是拿来怎么使用而已，我觉得大家想用其实可以自己集成也挺好的

**Comment by 8debug** [comment]
作者可以考虑试试 kodein

**Comment by hegaojian** [comment]
已经有好多人向我推荐了kodein，我会考虑试试的
