### ISSUE TITLE
作者为何用AndroidViewModel？

### ISSUE THREAD

**Issue by by8023hxy** [hegaojian/JetpackMvvm#17]
之前一直关注作者写的demo，今天下了新demo看，改动好大啊，尤其是新的BaseViewModel。并没有看到在ViewModel里用到application。再就是初始化viewmodel的方式着实累了点。可以参考private val  requestViewModel :RequestAriticleViewModel by viewModels(),直接使用ktx中的扩展函数就好。

**Comment by hegaojian** [comment]
之所以用AndroidViewModel是为了满足某些用户的需求需要在viewmodel中用到上下文，换成了AndroidViewModel其实就是兼容性提高了点，但是我开发中好像没有在viewmodel中用到过上下文...后面优化下吧，写2个BaseViewMoudel 一个继承AndroidViewModel 一个继承ViewMoudel供大家自己选择

这个ktx得拓展函数我还真不知道....知识点还是太浅了啊哈哈， 我自己写的现在看起来有点画蛇添足了，非常感谢你得提示

**Comment by by8023hxy** [comment]
好的谢谢作者的回复。
哈哈，那个扩展函数我也是最近才有学到，ktx中有很多东西确实很方便。
