### ISSUE TITLE
BaseVmDbActivity 和 BaseVmActivity 有重复的代码，为什么继承实现呢？

### ISSUE THREAD

**Issue by KevinChang007** [hegaojian/JetpackMvvm#18]
abstract class BaseVmDbActivity<VM : BaseViewModel, DB : ViewDataBinding> : BaseVmActivity<VM>() {

    lateinit var mDatabind: DB

    /**
     * 创建DataBinding
     */
    override fun createContentView() {
        mDatabind = DataBindingUtil.setContentView(this, layoutId())
        mDatabind.lifecycleOwner = this
    }
}

**Comment by KevinChang007** [comment]
BaseVmDbFragment 和 BaseVmFragment 也是一样的问题。
没有继承有特殊情况的考虑吗？

**Comment by hegaojian** [comment]
abstract class BaseVmDbActivity<VM : BaseViewModel, DB : ViewDataBinding> : AppCompatActivity() { 兄弟你是不是看错了，我的BaseVmDbActivity没有继承BaseVmDbActivity啊，你拉下代码看看

**Comment by hegaojian** [comment]
abstract class BaseVmDbActivity<VM : BaseViewModel, DB : ViewDataBinding> : AppCompatActivity() { 兄弟你是不是看错了，我的BaseVmDbActivity没有继承BaseVmActivity啊，你拉下代码看看

**Comment by KevinChang007** [comment]
我没写清楚，上面的代码是我改过后的。源代码为什么不继承呢 ？有特殊考虑吗

**Comment by KevinChang007** [comment]
BaseViewModelExt.kt 中也有较多重复的代码！  ￣□￣｜｜

**Comment by hegaojian** [comment]
因为当时考虑到有些人不想用Databinding，所以写了2种基类，
BaseVmDbActivity支持ViewModel，Databinding的泛型传入
BaseVmActivity仅有ViewModel，将Databinding相关的代码给去掉了
但是经你这么一说，这么写确实显得太low了，BaseVmDbActivity可以直接继承BaseVmActivity就好了，能减少很多重复代码，也好维护了...... 当时可能脑子抽了吧，没想到这一层:satisfied::satisfied::satisfied:
