### ISSUE TITLE
给菜鸡作者提个bug

### ISSUE THREAD

**Issue by hegaojian** [hegaojian/JetpackMvvm#19]
Demo中进入SettingFragment（设置界面）后，不管做什么操作，退出该Fragment后，操作其他的任何界面变多了以后会变的卡顿（可以试试项目模块）......如果直接写一个SettingActivity去包裹SettingFragment，退出该SettingActivity就不会有卡顿的问题。
目前发现原因大概是PreferenceFragmentCompat该类的锅，记录一下放在这里，大家如果发现有好的解决方案也可以提一下

**Comment by zhuyu1022** [comment]
“不然我加他个鸡儿加”，看到这个注释笑死我了，哈哈

**Comment by hegaojian** [comment]
这都被你发现了 :joy::joy::joy:  @zhuyu1022
