### ISSUE TITLE
HeadInterceptor 的bug

### ISSUE THREAD

**Issue by 8debug** [hegaojian/JetpackMvvm#21]
我正在将此项目改造成适用于我公司业务的项目，在此过程中发现在给HeadInterceptor 传递header时有些问题
![image](https://user-images.githubusercontent.com/3394927/84473707-1ab32a80-acbc-11ea-9c01-59ab99295bd7.png)
如图所示，从登录界面到首界面 HeadInterceptor 内方法体被调用时 headers 参数始终为空

**Comment by hegaojian** [comment]
这种方式不太好是我考虑不周，你可以换一种方式写
```
/**
 * 自定义头部参数拦截器，传入heads
 */
class MyHeadInterceptor : Interceptor {

    @Throws(IOException::class)
    override fun intercept(chain: Interceptor.Chain): Response {
        val builder = chain.request().newBuilder()
        builder.addHeader("token", "token123456").build()
        builder.addHeader("device", "Android").build()
        return chain.proceed(builder.build())
    }

}
```
直接自定义一个自己的HeadInterceptor  添加进去就好了，你可以看看最新的demo
