### ISSUE TITLE
base UI类的  loadingChange  在使用中并没有触发

### ISSUE THREAD

**Issue by benBaby** [hegaojian/JetpackMvvm#33]
mViewModel.loadingChange.showDialog.observe(viewLifecycleOwner, Observer {
            showLoading(it)
        })
        mViewModel.loadingChange.dismissDialog.observe(viewLifecycleOwner, Observer {
            dismissLoading()
        })

**Comment by hegaojian** [comment]
你的版本号是多少

**Comment by liuya891012** [comment]
草，多年以后我也发现了这个问题，loadingChange在整个项目中没用，mViewModel.loadingChange.showDialog.observeInFragment永远不会触发
