### ISSUE TITLE
有什么方法可以  代替 onresume吗？

### ISSUE THREAD

**Issue by ppg408331701** [hegaojian/JetpackMvvm#34]
目前使用的是修改过的navigation，理论不会触发重绘，但是也带来了新的问题，
A ---> B    再从B --->A 时，假如不考虑viewpager之类的情况

有什么好办法可以在A页面监听返回事件吗？ 类似activity的onresume

大概就是某个页面需要返回时刷新一下

**Comment by ppg408331701** [comment]
fragment的onresume只在viewpager才有效

**Comment by hegaojian** [comment]
可以重写onHideChange方法来判断

**Comment by ppg408331701** [comment]
嗯，确实可以

配合evenlivedata，通知viewpager里面的子页面也能刷新。
