### ISSUE TITLE
大佬 你好  我请问哈这里的网络请求咋个通过协程在io线程执行的呢  （没看到withContext(Dispatchers.IO)）

### ISSUE THREAD

**Issue by NickTet** [hegaojian/JetpackMvvm#36]
![image](https://user-images.githubusercontent.com/14065751/93185452-00339600-f770-11ea-9942-27b6ad6b210a.png)

**Comment by hegaojian** [comment]
为什么没看到withContext(Dispatchers.IO)，是因为retrofit在执行 suspend 标记的函数时，会自动切到 IO 线程 ，所以不需要我们再处理切换了

**Comment by NickTet** [comment]
我看retroift的源码不都还是java的吗  咋个会支持suspend呢  能截个图看看retrofit网络切换那部分代码吗

**Comment by hegaojian** [comment]
源码我没有具体研究，是之前看 扔物线公开课 里面他说的

**Comment by NickTet** [comment]
好吧 谢谢大佬 我关闭这个issure了
