### ISSUE TITLE
SwipeRefreshLayout 和ViewPager2滑动冲突是怎么处理的？

### ISSUE THREAD

**Issue by ffaa30703** [hegaojian/JetpackMvvm#37]
我没看到你项目里有针对SwipeRefreshLayout 和ViewPager2滑动冲突处理，可你的项目不会有冲突

**Comment by hegaojian** [comment]
我并没有处理啊，因为他们本身就没有什么冲突

**Comment by ffaa30703** [comment]
找到问题了，loadservice 初始化在recycleview上就会产生这个冲突
