### ISSUE TITLE
关于网络请求，后台数据请求code 200  data为空的时候出错

### ISSUE THREAD

**Issue by lewmm** [hegaojian/JetpackMvvm#38]
用了你的框架来重构 发现 后台如果没设置参数data为空的时候 由于kotlin的原因   用BaseViewModel.request请求 在BaseViewModelExt.kt解析数据的时候 会报出 Parameter specified as non-null is null: method kotlin.jvm.internal.Intrinsics.checkParameterIsNotNull, parameter it的错误   
如果用requestNoCheck来请求 在解析又会多一步操作来处理   -0 - 不用想用这个方法  。 
请问有什么办法来处理这个问题吗

**Comment by hegaojian** [comment]
如果data可为null的情况下，你需要在你的返回值泛型中加个 ？ 
示例 ：
```
 /**
     * 收藏文章
     */
    @POST("lg/collect/{id}/json")
    suspend fun collect(@Path("id") id: Int): ApiResponse<Any?>
```
