### ISSUE TITLE
UnPeekLiveData的疑问

### ISSUE THREAD

**Issue by android-1995** [hegaojian/JetpackMvvm#44]
🐔哥
me.hgj.jetpackmvvm.callback.livedata.event.EventLiveData和me.hgj.jetpackmvvm.callback.livedata.UnPeekLiveData有啥区别呀？为啥感觉都是防止旧数据倒灌的情况？

**Comment by hegaojian** [comment]
框架中最新版的 EventLiveData 是继承 [https://github.com/KunMinX/UnPeek-LiveData](https://github.com/KunMinX/UnPeek-LiveData)，作为界面通信的作用，也防止旧数据倒灌，支持释放内存，

框架中的UnPeekLiveData是根据反射干预 Version（存在延迟缺陷） 的方式封装的，当时是为了防止数据倒灌而加的，后面在考虑是否要弃用

**Comment by android-1995** [comment]
> 框架中最新版的 EventLiveData 是继承 https://github.com/KunMinX/UnPeek-LiveData，作为界面通信的作用，也防止旧数据倒灌，支持释放内存，
> 
> 框架中的UnPeekLiveData是根据反射干预 Version（存在延迟缺陷） 的方式封装的，当时是为了防止数据倒灌而加的，后面在考虑是否要弃用

当前是否可以用**EventLiveData** 替代 **框架中的UnPeekLiveData**呢？貌似框架中的UnPeekLiveData也没几处使用。

**Comment by hegaojian** [comment]
可以替代的

**Comment by android-1995** [comment]
好的，🐔哥
