### ISSUE TITLE
请教一个关于Navigation组件返回重建页面的问题

### ISSUE THREAD

**Issue by Quyunshuo** [hegaojian/JetpackMvvm#48]
我看大佬的项目中使用Navigation组件并没有出现返回时页面重建的现象，我也只是粗略的看了看项目中有一些重写Navigation相关的类，大佬能否分享下解决方案

**Comment by hegaojian** [comment]
官方对 fragment navigate 方法是设计是通过 replace 完成的。这造成了返回时界面被重绘。解决方案就是重写和替换上自己的 FragmentNavigator，使用 add / hide 方式实现  
具体可参考这位大佬写的文章:  https://xiaozhuanlan.com/topic/5860149732

**Comment by Quyunshuo** [comment]
谢大佬
