### ISSUE TITLE
fragment切换时有卡顿

### ISSUE THREAD

**Issue by benxin123** [hegaojian/JetpackMvvm#49]
fragment用懒加载，切换动画还没执行完毕时数据就已经加载好了，这时页面会有渲染卡顿，有什么好办法解决吗？暂时用postDelayed 500 可以解决

**Comment by hegaojian** [comment]
这个问题之前有人提过，单Activity模式都有这个问题，解决方案暂时也是你说的这种 用postDelayed 延迟，延迟时间可以设置比转场动画时间长一点
