### ISSUE TITLE
服务器返回的内容就是一个字符串比如"/picth/2000/test.jpg"，这个怎么处理？

### ISSUE THREAD

**Issue by 429329513wanting** [hegaojian/JetpackMvvm#50]
现在如果返回不是json格式，就报解析错误。我想直接获取到这个字符串

**Comment by hegaojian** [comment]
可以使用不脱壳的请求方式，定义retrofit接口时 返回值定义为String

**Comment by 429329513wanting** [comment]
现在遇到这种情况，返回的body是个网页格式 <!DOCTYPE html> <html> <head> 

vm:
var testResult = MutableLiveData<ResultState<String>>()
接口定义：
 suspend fun test(@QueryMap params: HashMap<String,String>):String
请求方式
requestNoCheck({ apiService.baiduInfo(header = header,params = params)},testResult,true)
结果错误信息显示:解析错误，请稍后再试1001Use JsonReader.setLenient(true) to accept malformed JSON at line 1 column 1 path $

按理说不会去解析这个网页了，结果还是报解析错误。是因为字符串是网页格式的原因吗？还是说如果是非json格式字符串都会报这个错

**Comment by hegaojian** [comment]
试试将返回值定义为 any 接收 看有没有问题

**Comment by 429329513wanting** [comment]
> 试试将返回值定义为 any 接收 看有没有问题

不行,同样的报错。感觉框架 处理 ResultState，还是涉及到解析了

**Comment by hegaojian** [comment]
让后台改改数据格式吧，这个应该是属于后台的工作，数据给的不规范，正常的不管成功失败，都应该返回一个固定的格式
