### ISSUE TITLE
登录 邮箱无法完整输入 登不上wanandroid账号

### ISSUE THREAD

**Issue by HAHH9527** [hegaojian/JetpackMvvm#54]
本人17位账号，最后一位输入不进去，是不是限制了最长16位

**Comment by hegaojian** [comment]
是的，一般就16位,17位是有点骚的

**Comment by HAHH9527** [comment]
> 是的，一般就16位,17位是有点骚的

不改一下吗😂

**Comment by hegaojian** [comment]
最新的二维码中已经可以支持 20位长度账号了

**Comment by HAHH9527** [comment]
> 最新的二维码中已经可以支持 20位长度账号了

好评👍

**Comment by hegaojian** [comment]
其实你把源码下载下来改下就好了，这个不是什么问题😂

**Comment by HAHH9527** [comment]
> 其实你把源码下载下来改下就好了，这个不是什么问题😂

懒（bushi，你能改好就有现成的用了
