### ISSUE TITLE
nav().navigateUp()返回上一个fragment不会调用该fragment.onResume事件

### ISSUE THREAD

**Issue by android-1995** [hegaojian/JetpackMvvm#55]
如题

**Comment by hegaojian** [comment]
官方对 fragment navigate 方法是设计是通过 replace 完成的。这造成了返回时界面被重绘。解决方案就是重写和替换上自己的 FragmentNavigator，使用 add / hide 方式实现，这也导致了一个问题，切换显示的时候不走onresume，而是走了onhidechange方法，你可以在这个方法中做你需要的操作
