### ISSUE TITLE
请问一下怎么处理嵌套请求呢？

### ISSUE THREAD

**Issue by FrankyLee-dev** [hegaojian/JetpackMvvm#56]
第二个请求需要第一个请求的结果
request({ api1 }, {
            // 请求成功
                      request({ api2(it) }, {
                      // 请求成功
                      
                  }, {
                      // 请求失败
                      
                  })
        }, {
            // 请求失败
            
        })
不会是这样吧。

**Comment by hegaojian** [comment]
可以参考一下 demo中 HttpRequestManger 类中的 注册并登陆请求
```
 /**
     * 注册并登陆
     */
    suspend fun register(username: String, password: String): ApiResponse<UserInfo> {
        val registerData = apiService.register(username, password, password)
        //判断注册结果 注册成功，调用登录接口
        if (registerData.isSucces()) {
            return apiService.login(username, password)
        } else {
            //抛出错误异常
            throw AppException(registerData.errorCode, registerData.errorMsg)
        }
    }
```

**Comment by FrankyLee-dev** [comment]
好的，谢谢
