### ISSUE TITLE
支持Jetpack Compose吗

### ISSUE THREAD

**Issue by lodgkk** [hegaojian/JetpackMvvm#58]
如题

**Comment by hegaojian** [comment]
目前暂未支持的，Compose这玩意儿我还没咋去学

**Comment by hegaojian** [comment]
目前暂未支持的，Compose这玩意儿我还没咋去学

**Comment by lodgkk** [comment]
就是向flutter靠拢

**Comment by lodgkk** [comment]
不过很不错,支持你,新项目用来看看

**Comment by Alexxiaopang** [comment]
compose 只是ui框架，你可以不使用xml就好了，这个和这一块没啥，但是要注意loadsir的状态图，这个全局转态会影响到

**Comment by hegaojian** [comment]
你可以用我另外一个项目 [MvvmHelper](https://github.com/hegaojian/MvvmHelper)  封装的东西更多一点，去除了Navigation
