### ISSUE TITLE
请求返回解析异常，请问这个有解决方案么

### ISSUE THREAD

**Issue by ll354385811** [hegaojian/JetpackMvvm#61]
当请求后获得结果为
{
    "ResultCode": 1,
    "Message": "********",
    "Data": ""
}
Data返回空串，4中解析方式都会直接进AppException,请求这个有解决方式么

**Comment by hegaojian** [comment]
你在定义这个Retrofit的接口，写的返回值如果不是String或者Any类型会报错的

你可以让你后台将Data没有值时数据返回为 null 

或者自己添加一个响应拦截器，判断值为“”的时候设置为null，再重新设置给response

**Comment by ll354385811** [comment]
好的，谢谢
