### ISSUE TITLE
作者什么时候  dataBinding 迁移到viewBinding 呢

### ISSUE THREAD

**Issue by D-zy** [hegaojian/JetpackMvvm#66]
去掉官方废弃的 kotlin-android-extensions插件

**Comment by hegaojian** [comment]
目前没有迁移到viewBinding的计划呢，因为使用dataBinding 也有viewBinding的效果，kotlin-android-extensions插件的话暂时先留着吧，虽然被官方废弃了，但是用着确实挺方便的，影响不大
