### ISSUE TITLE
有java版本的实现

### ISSUE THREAD

**Issue by arafat5549** [hegaojian/JetpackMvvm#7]
希望能有java版本的实现重写

**Comment by hegaojian** [comment]
目前重构ing，在优化规范写法与简化操作，该库是基于Kotlin编写的，像封装的kotlin协程+retrofit，各种拓展函数封装，Kotlin是该库的核心，所以不会去基于Java重写。
我认为Kotlin是主流，是我们原生开发者现在必须要去学习的语言，而且Kotlin比Java香太多了,老哥赶紧换吧，真心推荐Kotlin
