### ISSUE TITLE
issue

### ISSUE THREAD

**Issue by hanayokana** [hegaojian/JetpackMvvm#70]
我想问一个问题哈。LoadSir我用的时候         setDefaultCallback(SuccessCallback::class.java)//设置默认加载状态页
如果用SuccessCallback的话在调用LoadSir.showLoading()的时候,Progressbar并不能显示出来，请问你是怎么设置的？

**Comment by hegaojian** [comment]
可能是你设置了showLoading的时候，后面LoadSir刚好加载View完成设置了 SuccessCallback

**Comment by hegaojian** [comment]
我的demo中因为都是Fragment，而且设置loading时都是在lazyLoadData中调用的，这时候loadSir已经注册完毕了，所以此时调用不会有你说的那种问题
但是在普通的Activity中处理的话，我处理方式是先注册view，然后等待view加载完成后再调用 showLoading等等后续方法 

```
//注册
...
LoadSir.getDefault().register(view)
 view.post {
            initView(savedInstanceState) //设置showLoading 及后续的操作都在这里面
        }
view
```

**Comment by hanayokana** [comment]
谢谢
