### ISSUE TITLE
Navigation 2.4.0 增加了包括多个返回堆栈在内的很多新功能

### ISSUE THREAD

**Issue by ppg408331701** [hegaojian/JetpackMvvm#72]
https://developer.android.google.cn/jetpack/androidx/releases/navigation

考虑到现在demo中是修改过的Navigation，建议作者可以看看。

我也在研究，希望可以使用原生的Navigation来实现跳转。

现在的Navigation是在太不方便了

**Comment by hegaojian** [comment]
学学学，天天学，脑壳都要学废掉了 :sob::sob::sob:
