### ISSUE TITLE
请教一下关于unpeek-livedata在项目中的问题

### ISSUE THREAD

**Issue by weizhizhu** [hegaojian/JetpackMvvm#75]
如果把unpeek-livedata升级到最新版本 6.0.0，是不是就不需要区分是否是observeInActivity、observeInFragment等这些 直接是普通的observe

**Comment by hegaojian** [comment]
刚看了一下，他的最新版6.0.0 使用方式 确实跟普通的 livedata一样的使用了，当然你升级以后修改的时候，记得 activity observe 用this，fragment observe 用viewLifecycleOwner

**Comment by weizhizhu** [comment]
感谢 感谢

**Comment by hegaojian** [comment]
客气了
