### ISSUE TITLE
快速来回切换2个不同的Fragemnt，会异常闪退

### ISSUE THREAD

**Issue by weizhizhu** [hegaojian/JetpackMvvm#76]
![image](https://user-images.githubusercontent.com/16060581/125951726-0529cefa-4277-4e94-a5f4-77573965cf4e.png)
这个绿色方框内报空，当前我的处理方案是在onDestroy中handler.removeCallbacksAndMessages

**Comment by hegaojian** [comment]
感谢大兄弟，发现了这个bug，并给出解决方案 ，稍后我更新一下 👍 👍 👍
