### ISSUE TITLE
返回服务器的泛型类用Any，回调报linkedtreemap不匹配   博主怎么统一转换的

### ISSUE THREAD

**Issue by 18810951092** [hegaojian/JetpackMvvm#80]

**Comment by 18810951092** [comment]
这个返回数据类型必须指定类吗？   不指定用Any,又说不匹配想要的指定类型

**Comment by 18810951092** [comment]
如果指定了数据返回类型   服务器返回的却不是你指定的类型，怎么解决

**Comment by hegaojian** [comment]
> 如果指定了数据返回类型 服务器返回的却不是你指定的类型，怎么解决

这个是规范问题，找后台协商好吧，指定了什么类型 就返回什么类型的数据
