### ISSUE TITLE
关于lazyLoadTime方法的一些问题。

### ISSUE THREAD

**Issue by ILoveYouCC** [hegaojian/JetpackMvvm#81]
/**
     * 延迟加载 防止 切换动画还没执行完毕时数据就已经加载好了，这时页面会有渲染卡顿  bug
     * 这里传入你想要延迟的时间，延迟时间可以设置比转场动画时间长一点 单位： 毫秒
     * 不传默认 300毫秒
     * @return Long
     */
    override fun lazyLoadTime(): Long {
        return 300
    }
这里延时300ms去加载数据，会导致页面会有一个短暂的闪屏。会显示一下页面再loading。体验不好。有什么方法解决么？这个不延时的bug具体是啥啊。请作者大大指点一下。

**Comment by hegaojian** [comment]
如果有影响的话你可以重写这个方法，传入你自己的时间为0，传为0也问题不大的

**Comment by ILoveYouCC** [comment]
目前时传了0的。之前有个handler的延时问题，不过已经改了。主要是看你写的注释说有个bug。我没搞懂是啥。
