### ISSUE TITLE
最近重构了一下，工作忙没时间写文档，大家可以看看demo 后面有时间我把文档更新下

### ISSUE THREAD

**Issue by hegaojian** [hegaojian/JetpackMvvm#9]

**Comment by chengxinping** [comment]
重构之后把liveData的viewmodel抽出来了？

**Comment by chengxinping** [comment]
现在一个界面有两个viewmodel 会不会不太好？livedata的model应该没必要继承baseViewmodel吧

**Comment by hegaojian** [comment]
分了2种Viewmodel，一种state的专门是负责与界面绑定数据的Viewmodel，还有一个就是request的专门负责拿数据（本地，网络），这样的话分工明确点，单一职责，可以减少Viewmodel的臃肿

**Comment by hegaojian** [comment]
如果你喜欢的话，也可以不分开，根据自己的喜好来写，demo只是个参考，具体怎么实现还得看开发者自己的理解，毕竟每个人的风格与思想不一样，也不是非要照着别人的模板来开发

**Comment by underwes** [comment]
这么好用的框架 大佬牛逼啊

**Comment by underwes** [comment]
给大佬顶一波
