### ISSUE TITLE
Navigation 启动新页面并关闭当前页面的功能如何实现？

### ISSUE THREAD

**Issue by wflian** [hegaojian/JetpackMvvm#90]
比如登录页面 LoginFragment  里面的登录按钮，登录成功以后  打开 MainFragment 并关闭 LoginFragment。这情况如何实现呢？

**Comment by hegaojian** [comment]
这是navigation的一个坑，我目前还没有发现有啥好的方法去支持这个业务，我建议你 将登陆页作为一个activity去写，登陆成功以后跳转到 main

**Comment by wflian** [comment]
这个场景不止这一个地方用吧！我觉得这种场景很常用呢

**Comment by hegaojian** [comment]
这种场景确实是比较常见的，但是目前navigation貌似不支持 从 `fragmentA` 跳转到 `尚未创建的fragmentB` 时关闭 `fragmentA` ，如果是 A ->B ->C  　　 C想跳转到A时关闭BC这个是支持的

**Comment by T-BayMax** [comment]
可以用尝试popBackStack或navigateUp

**Comment by T-BayMax** [comment]
https://developer.android.google.cn/guide/navigation/navigation-navigate

**Comment by wflian** [comment]
findNavController().navigate(
                R.id.action_splashFragment_to_mainFragment,
                bundleOf(MainFragment.usernameKey to "Alex Gladkov"),
                navOptions {
                    anim {
                        enter = R.anim.nav_default_enter_anim
                        popEnter = R.anim.nav_default_pop_enter_anim
                        popExit = R.anim.nav_default_pop_exit_anim
                        exit = R.anim.nav_default_exit_anim
                    }
                    launchSingleTop = true
                    popUpTo(R.id.nav_graph_application) {
                        inclusive = true
                    }
                }
这种方式可以实现。
另外还有一个问题：一个Fragment启动自己本身 为啥没反应，启动失败

<action
android:id="@+id/action_testFragment_self"
app:destination="@id/testFragment"
app:enterAnim="@anim/slide_in_right"
app:exitAnim="@anim/slide_out_left"
app:popEnterAnim="@anim/slide_in_left"
app:popExitAnim="@anim/slide_out_right"
/>

**Comment by android-taoge** [comment]
直接在action里加入最后两行，可以实现跳转到目标页面，并关闭之前页面
 <action
        android:id="@+id/action_to_mainFragment"
        app:destination="@id/mainFragment"
        app:enterAnim="@anim/slide_in_right"
        app:exitAnim="@anim/slide_out_left"
        app:popEnterAnim="@anim/slide_in_left"
        app:popExitAnim="@anim/slide_out_right"
        app:popUpTo="@id/mainFragment"
        app:popUpToInclusive="true" />
