### ISSUE TITLE
如何在dialog中，或者自定义控件中使用viewmodel？

### ISSUE THREAD

**Issue by SheepYang1993** [hegaojian/JetpackMvvm#92]
当控件或dialog销毁的时候，viewmodel也销毁？

**Comment by hegaojian** [comment]
viewmodel 一般是由 activity 或者 fragment生成的，生命周期还很长，一般不建议在dialog和自定义view中使用,你可以将方法回调出来给 持有viewmodel 的 activity或 fragment调用

**Comment by SheepYang1993** [comment]
> viewmodel 一般是由 activity 或者 fragment生成的，生命周期还很长，一般不建议在dialog和自定义view中使用,你可以将方法回调出来给 持有viewmodel 的 activity或 fragment调用

恩嗯，现在写成回调出来了。viewmodel生命周期毕竟都是activity 或者 fragment在管理的，还是放在activity里fragment里面比较合适
