### ISSUE TITLE
EventViewModel在observe的activity中使用，如果activity处于pause状态，页面被遮盖，无法监听到

### ISSUE THREAD

**Issue by AutumnLeavesss** [hegaojian/JetpackMvvm#93]
EventViewModel在observe的activity中使用，如果activity处于pause状态，页面被遮盖，无法监听到

**Comment by hegaojian** [comment]
是这样子的，liveData 生命周期在 start -> pause之间才会被立即监听到

**Comment by getglory** [comment]
只有页面是激活状态才能收到
