### ISSUE TITLE
为啥很少用databinding来绑定数据？

### ISSUE THREAD

**Issue by ifadai** [hegaojian/JetpackMvvm#97]
最近在学习这个项目，看了项目大概代码，发现很少把实体类传到xml中，用databinding来绑定数据，大都是在java（kotlin）代码中给控件设置文字、图片。这是基于啥考虑的啊？是databinding有啥不方便的地方吗？诚心问一下，看的时候很疑惑，，，

**Comment by SaltedFish-Extreme** [comment]
> 最近在学习这个项目，看了项目大概代码，发现很少把实体类传到xml中，用databinding来绑定数据，大都是在java（kotlin）代码中给控件设置文字、图片。这是基于啥考虑的啊？是databinding有啥不方便的地方吗？诚心问一下，看的时候很疑惑，，，

全用databinding学习成本太高了吧，代码看起来更乱了，在代码里设置不也挺好吗，还不用生成反射文件🤔

**Comment by hegaojian** [comment]
当时在写这个项目的时候，想着是mvvm架构，于是就用了databinding，但是实际写的时候，用databinding去绑定 xml，对于我来说这太难受了，于是后面就很少用databingind。但是也不好去掉，虽然我不喜欢，可能其他的开发兄弟们爱用。用于不用看个人感受吧，不可能所有人都按照一个标准去开发，那不太现实。

**Comment by hegaojian** [comment]
当时在写这个项目的时候，想着是mvvm架构，于是就用了databinding，但是实际写的时候，用databinding去绑定 xml，对于我来说这太难受了，于是后面就很少用databingind。但是也不好去掉，虽然我不喜欢，可能其他的开发兄弟们爱用。用于不用看个人感受吧，不可能所有人都按照一个标准去开发，那不太现实。

**Comment by ifadai** [comment]
> 当时在写这个项目的时候，想着是mvvm架构，于是就用了databinding，但是实际写的时候，用databinding去绑定 xml，对于我来说这太难受了，于是后面就很少用databingind。但是也不好去掉，虽然我不喜欢，可能其他的开发兄弟们爱用。用于不用看个人感受吧，不可能所有人都按照一个标准去开发，那不太现实。

好的，谢谢，我还以为大家都在用databinding，就我落伍了，原来大家很多也不太喜欢，，哈哈。
